import type {
  Property,
  SearchHistoryItem,
  SavedProperty,
} from "@/types/property";

// Placeholder images for properties
const propertyImages = [
  "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
  "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
  "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
  "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
  "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
  "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
  "https://images.unsplash.com/photo-1598228723793-52759bba239c?w=800&q=80",
];

export const mockProperties: Property[] = [
  {
    id: "1",
    propertyId: "AZ00022",
    address: "1224 Riverside Road",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[0],
    images: propertyImages,
    daysOnMarket: 10,
    daysLeft: 45,
    status: "vacant",
    tags: ["AMH-built", "Built 2025", "Vacant"],
    amenities: ["Pool", "Garage", "Central AC"],
    yearBuilt: 2025,
    lotSize: 5500,
    propertyType: "single-family",
    description:
      "This two-story household at 1224 Riverside Road features a kitchen equipped with mixed appliances and quartz countertops. Residents will appreciate the tile flooring throughout the main living areas. Architectural highlights include arched windows and a vaulted ceiling, adding visual interest to the space. The primary bathroom offers a dual-vanity setup for added convenience. Outdoor amenities include a two-car garage and a double-width driveway. This two-story household at 1224 Riverside Road features a kitchen equipped with mixed appliances and quartz countertops. Residents will appreciate the tile flooring throughout the main living areas. Architectural highlights include arched windows and a vaulted ceiling, adding visual interest to the space. The primary bathroom offers a dual-vanity setup for added convenience. Outdoor amenities include a two-car garage and a double-width driveway.",
    features: {
      garageAndParking: ["2 Car Garage", "2 Car Garage"],
      yardAndExterior: ["Front Yard Grass", "Front Yard Grass"],
      kitchen: [
        "Pantry, Single Sink, Black Dishwasher, Kitchen Island, Light Cabinets, Chandelier.",
      ],
      bedroomAndBath: [
        "En Suite, Separate Shower, Walk-In Closet, Arched Window.",
      ],
      flooringAndFinish: [
        "Tile Flooring, Luxury Vinyl Plank Flooring, Vaulted Ceilings.",
      ],
    },
    nearbyPlaces: [
      {
        id: "1",
        name: "Desert Ridge High School",
        category: "school",
        distance: "1.3mi",
        time: "32min",
      },
      {
        id: "2",
        name: "Highland High School",
        category: "school",
        distance: "2.0mi",
        time: "1.2hr",
      },
      {
        id: "3",
        name: "Eastmark High School",
        category: "school",
        distance: "3.5mi",
        time: "2.0hr",
      },
      {
        id: "4",
        name: "Mesa Market Place Swap",
        category: "retail",
        distance: "0.5mi",
        time: "10min",
      },
      {
        id: "5",
        name: "Superstition Gateway West",
        category: "retail",
        distance: "1.2mi",
        time: "32min",
      },
      {
        id: "6",
        name: "Monte Vista Village Center",
        category: "retail",
        distance: "2.0mi",
        time: "1.6hr",
      },
      {
        id: "7",
        name: "9455 E. Neville Ave",
        category: "parking",
        distance: "0.15mi",
        time: "12min",
      },
      {
        id: "8",
        name: "Signal Butte Park Parking",
        category: "parking",
        distance: "2.0mi",
        time: "2.0hr",
      },
      {
        id: "9",
        name: "EoS Fitness",
        category: "gym",
        distance: "1.3mi",
        time: "1.2hr",
      },
      {
        id: "10",
        name: "LA Fitness",
        category: "gym",
        distance: "2.0mi",
        time: "2.3hr",
      },
    ],
    rentalSalesComps: {
      purchaseCosts: 25,
      rehabCosts: 75,
    },
  },
  {
    id: "2",
    propertyId: "AZ00023",
    address: "7751 Dartmouth Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 3,
    baths: 3,
    sqft: 1600,
    imageUrl: propertyImages[1],
    images: propertyImages.slice(1, 6),
    daysOnMarket: 18,
    daysLeft: 28,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Vacant"],
    amenities: ["Pool", "Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Beautiful single-family home with modern amenities.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Front Yard Grass", "Backyard"],
      kitchen: ["Granite Countertops, Stainless Steel Appliances"],
      bedroomAndBath: ["Master Suite, Walk-In Closet"],
      flooringAndFinish: ["Hardwood Floors, Crown Molding"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 30, rehabCosts: 70 },
  },
  {
    id: "3",
    propertyId: "AZ00024",
    address: "8683 Dancliff Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[2],
    images: propertyImages.slice(2, 7),
    daysOnMarket: 10,
    daysLeft: 55,
    status: "vacant",
    tags: ["AMH Built", "Built 2025", "Vacant"],
    amenities: ["Pool", "Garage", "Central AC"],
    yearBuilt: 2025,
    propertyType: "single-family",
    description: "Newly built home with premium finishes.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Landscaped Yard"],
      kitchen: ["Quartz Countertops, Modern Appliances"],
      bedroomAndBath: ["4 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Luxury Vinyl Plank"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 20, rehabCosts: 80 },
  },
  {
    id: "4",
    propertyId: "AZ00025",
    address: "1411 Plateau Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 3,
    baths: 2,
    sqft: 1600,
    imageUrl: propertyImages[3],
    images: propertyImages.slice(3, 8),
    daysOnMarket: 10,
    daysLeft: 40,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Vacant"],
    amenities: ["Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Comfortable family home in great location.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Front and Back Yard"],
      kitchen: ["Open Concept Kitchen"],
      bedroomAndBath: ["3 Bedrooms, 2 Baths"],
      flooringAndFinish: ["Tile and Carpet"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 35, rehabCosts: 65 },
  },
  {
    id: "5",
    propertyId: "AZ00026",
    address: "7751 Dartmouth Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[4],
    images: propertyImages.slice(4, 9),
    daysOnMarket: 12,
    daysLeft: 22,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Vacant"],
    amenities: ["Pool", "Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Spacious home with pool access.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Pool", "Patio"],
      kitchen: ["Modern Kitchen"],
      bedroomAndBath: ["4 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Premium Flooring"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 25, rehabCosts: 75 },
  },
  {
    id: "6",
    propertyId: "AZ00027",
    address: "1224 Riverside Road",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 3,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[5],
    images: propertyImages.slice(5, 10),
    daysOnMarket: 25,
    daysLeft: 15,
    status: "occupied",
    tags: ["AMH Built", "Built 2025", "Compound"],
    amenities: ["Garage", "Central AC"],
    yearBuilt: 2025,
    propertyType: "single-family",
    description: "Part of compound community.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Community Grounds"],
      kitchen: ["Upgraded Appliances"],
      bedroomAndBath: ["3 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Tile Throughout"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 40, rehabCosts: 60 },
  },
  {
    id: "7",
    propertyId: "AZ00028",
    address: "1411 Plateau Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[6],
    images: propertyImages.slice(0, 5),
    daysOnMarket: 35,
    daysLeft: 10,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Rent"],
    amenities: ["Pool", "Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Available for rent.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Large Backyard"],
      kitchen: ["Full Kitchen"],
      bedroomAndBath: ["4 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Mixed Flooring"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 30, rehabCosts: 70 },
  },
  {
    id: "8",
    propertyId: "AZ00029",
    address: "1224 Riverside Road",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 3,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[7],
    images: propertyImages.slice(1, 6),
    daysOnMarket: 12,
    daysLeft: 38,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Vacant"],
    amenities: ["Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Well-maintained property.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Maintained Yard"],
      kitchen: ["Standard Kitchen"],
      bedroomAndBath: ["3 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Carpet and Tile"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 25, rehabCosts: 75 },
  },
  {
    id: "9",
    propertyId: "AZ00030",
    address: "1411 Plateau Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[8],
    images: propertyImages.slice(2, 7),
    daysOnMarket: 95,
    daysLeft: 33,
    status: "occupied",
    tags: ["Compound", "Built 2025", "Aged"],
    amenities: ["Pool", "Garage", "Central AC"],
    yearBuilt: 2025,
    propertyType: "single-family",
    description: "Premium compound property.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Community Pool Access"],
      kitchen: ["Gourmet Kitchen"],
      bedroomAndBath: ["4 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Hardwood"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 35, rehabCosts: 65 },
  },
  {
    id: "10",
    propertyId: "AZ00031",
    address: "1411 Plateau Drive",
    city: "Lake Dallas",
    state: "TX",
    zipCode: "76002",
    price: 2500,
    beds: 4,
    baths: 2.5,
    sqft: 1600,
    imageUrl: propertyImages[9],
    images: propertyImages.slice(3, 8),
    daysOnMarket: 30,
    daysLeft: 5,
    status: "vacant",
    tags: ["AMH Built", "Built 2020", "Rent"],
    amenities: ["Garage"],
    yearBuilt: 2020,
    propertyType: "single-family",
    description: "Ready for new tenants.",
    features: {
      garageAndParking: ["2 Car Garage"],
      yardAndExterior: ["Fenced Yard"],
      kitchen: ["Updated Kitchen"],
      bedroomAndBath: ["4 Bedrooms, 2.5 Baths"],
      flooringAndFinish: ["Luxury Vinyl"],
    },
    nearbyPlaces: [],
    rentalSalesComps: { purchaseCosts: 28, rehabCosts: 72 },
  },
];

export const mockSearchHistory: SearchHistoryItem[] = [
  {
    id: "1",
    query: "Vacant Homes — Lake Dallas, TX",
    matches: 26,
    filters: "Avg Price: $465K • Ready: 18",
    timestamp: new Date(),
    category: "today",
  },
  {
    id: "2",
    query: "New Listings — Mesa, Arizona",
    matches: 32,
    filters: "Under : $400K",
    timestamp: new Date(),
    category: "today",
  },
  {
    id: "3",
    query: "Homes with Pools — Frisco, TX",
    matches: 10,
    filters: "Needs Rehab",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "4",
    query: "Homes Near Schools — Gilbert, AZ",
    matches: 21,
    filters: "Rent Potential: $2,300/mo",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "5",
    query: "Vacant Homes — Lake Dallas, TX",
    matches: 26,
    filters: "Avg Price: $465K • Ready: 18",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "6",
    query: "New Listings — Mesa, Arizona",
    matches: 32,
    filters: "Under : $400K",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "7",
    query: "New Listings — Mesa, Arizona",
    matches: 32,
    filters: "Under : $400K",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "8",
    query: "New Listings — Mesa, Arizona",
    matches: 32,
    filters: "Under : $400K",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
  {
    id: "9",
    query: "New Listings — Mesa, Arizona",
    matches: 32,
    filters: "Under : $400K",
    timestamp: new Date(Date.now() - 86400000),
    category: "yesterday",
  },
];

export const mockSavedProperties: SavedProperty[] = mockProperties
  .slice(0, 4)
  .map((property, index) => ({
    id: `saved-${index}`,
    property,
    savedAt: new Date(),
  }));

export function getPropertyById(id: string): Property | undefined {
  return mockProperties.find((p) => p.id === id || p.propertyId === id);
}

export function searchProperties(query: string): Property[] {
  const lowercaseQuery = query.toLowerCase();
  return mockProperties.filter(
    (p) =>
      p.address.toLowerCase().includes(lowercaseQuery) ||
      p.city.toLowerCase().includes(lowercaseQuery) ||
      p.state.toLowerCase().includes(lowercaseQuery) ||
      p.zipCode.includes(lowercaseQuery),
  );
}

export function filterProperties(filters: {
  location?: string;
  status?: string;
  amenities?: string[];
}): Property[] {
  return mockProperties.filter((property) => {
    if (
      filters.location &&
      !`${property.city}, ${property.state}`
        .toLowerCase()
        .includes(filters.location.toLowerCase())
    ) {
      return false;
    }
    if (filters.status && property.status !== filters.status) {
      return false;
    }
    if (
      filters.amenities &&
      filters.amenities.length > 0 &&
      !filters.amenities.every((a) =>
        property.amenities
          .map((am) => am.toLowerCase())
          .includes(a.toLowerCase()),
      )
    ) {
      return false;
    }
    return true;
  });
}
